version: "3.8"

services:
  db:
    image: postgres:15
    container_name: livraria_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livraria
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./liv_back
    image: livraria_back:0.1-RELEASE
    container_name: livraria_backend
    depends_on:
      - db
    env_file:
      - ./liv_back/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./liv_front
    image: livraria_front:0.1-RELEASE
    container_name: livraria_frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  postgres_data:
