
FROM node:24-alpine AS builder
LABEL maintainer="GabrielRS"

WORKDIR /app


COPY liv_back/package*.json ./
RUN npm install


COPY liv_back .


RUN npm install --save @nestjs/cli
RUN npm install class-validator class-transformer

RUN npx nest build


FROM node:24-alpine

WORKDIR /app


COPY liv_back/package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
ENV PORT=3000

CMD ["node", "dist/main"]
