services:
  - type: web
    name: liv-back
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Livraria
          property: connectionString
      - key: FRONTEND_URL
        value: https://portfolio-gabriel-rodrigues-siqueiras-projects.vercel.app/
